#!/bin/bash
while read INPUT; do
        [[ -z "$INPUT" ]] && break
        eval $INPUT
done
source /etc/policy-bash/policy-conf

if [ -d $POLICIESDIR ]; then
	if [ -d $POLICIESDIR/$protocol_state ]; then
		cd $POLICIESDIR/$protocol_state
		for p in *.sh; do 
			if [ -f $p ]; then 
				POLICYNAME=$(basename $p .sh)
				logging "${protocol_state}/${POLICYNAME}" "Executing $POLICYNAME in smtp state $protocol_state"
				source $p; 
			fi; 
		done
	fi
fi

dunno
