#!/bin/bash
logging(){
	if [ -z "$POLICYNAME" ]; then POLICYNAME=default; fi
	logger -t "policy-bash[${protocol_state}/${POLICYNAME}]" -- $@
}
debug(){
	if [ $LOGLEVEL -eq 3 ]; then logging $@; fi
}
info(){
	if [ $LOGLEVEL -ge 2 ]; then logging $@; fi
}
pbsql(){
	debug "SQL Exec: $@"
	$MYSQL "$@"
}
policyreturn(){
	ACTION=$1; shift
	debug "Return action $ACTION"
	echo "action=$ACTION $@"
	echo "";
	exit 0
}
accept(){ 
	policyreturn "OK" 
}
ret4(){ 
	RET=$1; shift; policyreturn $RET $@ 
}
ret5(){ 
	RET=$1; shift; policyreturn $RET $@ 
}
reject(){ 
	policyreturn REJECT $@ 
}
defer(){ 
	policyreturn DEFER $@ 
}
defer_if_reject(){ 
	policyreturn defer_if_refect $@ 
}
defer_if_permit(){ 
	policyreturn defer_if_permit $@ 
}
discard(){ 
	policyreturn discard $@ 
}
dunno(){ 
	policyreturn DUNNO 
}
hold(){ 
	policyreturn HOLD $@ 
}
warn(){ 
	policyreturn WARN $@ 
}
